// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Token int32

const (
	Token_TODO Token = 0
)

var Token_name = map[int32]string{
	0: "TODO",
}
var Token_value = map[string]int32{
	"TODO": 0,
}

func (x Token) String() string {
	return proto.EnumName(Token_name, int32(x))
}
func (Token) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_token_f9d6ed0c93911a6d, []int{0}
}

func init() {
	proto.RegisterEnum("pb.Token", Token_name, Token_value)
}

func init() { proto.RegisterFile("token.proto", fileDescriptor_token_f9d6ed0c93911a6d) }

var fileDescriptor_token_f9d6ed0c93911a6d = []byte{
	// 63 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xc9, 0xcf, 0x4e,
	0xcd, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0xd2, 0x12, 0xe4, 0x62, 0x0d,
	0x01, 0x09, 0x09, 0x71, 0x70, 0xb1, 0x84, 0xf8, 0xbb, 0xf8, 0x0b, 0x30, 0x24, 0xb1, 0x81, 0x65,
	0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2e, 0xd1, 0xf6, 0x8e, 0x2c, 0x00, 0x00, 0x00,
}
